name: Deploy Javaweb
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: build project
        run: gradle clean build --no-daemon

      - name: Set permissions for yml
        run: chmod +x ./.github/workflows/actions/aws_creds.yml

      - name: load aws creds
        uses: ./.github/workflows/actions/aws_creds.yml

